name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          persist-credentials: false
          lfs: true

      - name: Build Project
        run: |
          npm cache clean --force
          npm ci
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          branch: gh-pages
          folder: build
          clean: true
          single-commit: true